### ISSUE TITLE
Get chunks for streaming

### ISSUE THREAD

**Issue by ahmed-troido** [KoljaB/RealtimeTTS#103]
Hi I'm using `GTTSEngine` to convert a text then stream the voice as chunks for the user.

```
def text_to_stream(self, text):
        self.stream.feed(text)
```

My question is, How to get chunks (as a result from engine) to stream it?

**Comment by KoljaB** [comment]
You can use the on_audio_chunk callback to get the chunks:

https://github.com/KoljaB/RealtimeTTS/blob/master/tests/test_on_audio_chunk_callback.py

**Comment by ahmed-troido** [comment]
thanks for help

**Comment by mvsoom** [comment]
Sending appreciation for this library. This is incredible. Thanks for open sourcing this!
