### ISSUE TITLE
Is it possible to have the next code proceed after the play_async() has completed its task?

### ISSUE THREAD

**Issue by gityeop** [KoljaB/RealtimeTTS#108]
```python
tts_stream.feed(response).play_async()
play_start_signal()
```
play() is outputting late, so I want to use play_async(). but in this case, all the following code is also executed, so the play_start_signal should come after the tts, but it comes before. Is there any way to solve this case?

**Comment by KoljaB** [comment]
Use on_audio_stream_stoo callback. Btw play() gets called by play_async() in a thread, so play_async is not outputting faster.

**Comment by gityeop** [comment]
Thank you! I tried using the `on_audio_stream_stop` callback, and it worked perfectly. I also understand now that `play_async()` does not output faster. Thanks again!
