### ISSUE TITLE
is styleTTS supported

### ISSUE THREAD

**Issue by itsPreto** [KoljaB/RealtimeTTS#11]
https://github.com/yl4579/StyleTTS2 seems very promising, was wondering if its supported by this library

**Comment by KoljaB** [comment]
The approach looks good. 

Must haves for a TTS to be included in RealtimeTTS:
- pip install 
- a realtime factor of <1 along with <8 GB VRAM usage (I don't want to only support absolute high end graphics card like 4090)
Nice to haves:
- streaming inference

They don't offer pip install currently, and I don't want losing this feature for RealtimeTTS and have people deal with stuff like git clone if possible. Would not be that hard to implement though looking at their requirements. I also need to check performance and streaming inference, currently I don't know if it's performant enough for realtime.

**Comment by Anon2578** [comment]
Yes adding Styletts will bring more better quality to open source tts

**Comment by KoljaB** [comment]
Ok, persuaded. Just tried the model and yep, speed and quality are really good. I'll integrate this as next engine soon.

**Comment by itsPreto** [comment]
> Ok, persuaded. Just tried the model and yep, speed and quality are really good. I'll integrate this as next engine soon.

How much work do you think it would be worth to support Silicon Macs? Most come with at least 16GB of unified RAM.

**Comment by KoljaB** [comment]
If the engine does not natively support Mac, chances are near zero I can do anything. Don't have one, can't test nothing.

To styletts I picked up so far:
- delivers quite good quality for english while being crazy fast
- seems to only support english and a bit japanese and chinese out of the box
- most other languages won't work or require some complicated training steps which are out of scope for RealtimeTTS (?, did not test this)
- iOS is not natively supported (?)

Languages and platforms may be bit of a bummer, need some more answers / research.

**Comment by KoljaB** [comment]
StyleTTS support added in [v0.4.19](https://github.com/KoljaB/RealtimeTTS/releases/tag/v0.4.19)
