### ISSUE TITLE
[Question] Is there a way to save the streamed audio to file?

### ISSUE THREAD

**Issue by salahzoubi** [KoljaB/RealtimeTTS#12]
I've managed to get the RealTimeTTS library to work, I'm wondering if there's anyway to save/keep appending audio chunks as they come in to a file so that I play it back later on? I want to listen to the output audio exactly as the stream will be playing it using the `play_async()` function. 

Thanks!

**Comment by KoljaB** [comment]
Not possible yet, but this is a great idea, I'll put in on the roadmap.

**Comment by salahzoubi** [comment]
Great! I also see that you can enable a parameter that logs synthesized speech, how do you access that once it's been logged?

**Comment by KoljaB** [comment]
Not implemented currently. How would you think about a callback for every sentence? Do you think, this hould this only be called after a sentence is synthesized or would you prefer to also have a callback right before synthesis?

**Comment by salahzoubi** [comment]
@KoljaB sohnds good! I think a callback once a sentence is synthesized is a better choice

**Comment by KoljaB** [comment]
For ever entity you feeded into the stream (string or generator), after calling play() it will try to extract a sentences from it until it can't (string is at end or generator is exhausted) and then synthesize the rest. So when using with LLMs it will basically wait for a sentence coming in.

**Comment by KoljaB** [comment]
v0.3.0 now allows audio file saving and play methods have a on_sentence_synthesized method. on_sentence_synthesized will be called before the sentence is being completely played back, so it's not a "sentence was just played" callback (since synthesis happens faster than playback if possible and their timings are independent).
