### ISSUE TITLE
I couldn't find an implementation for RealtimeRVC

### ISSUE THREAD

**Issue by seekkii** [KoljaB/RealtimeTTS#123]
I was trying to compile xtts_rvc_tester.py in example_rvc, and couldn't find an implementation for RealtimeRVC. 
Saw this line but not sure where should I import it from : from rvc.realtimervc import RealtimeRVC

**Comment by KoljaB** [comment]
I forgot to upload the folder, I'm sorry. You can find it [here](https://github.com/KoljaB/RealtimeTTS/tree/master/example_rvc/rvc) now.
