### ISSUE TITLE
Can it support GPT-SoVITS?

### ISSUE THREAD

**Issue by SinlinLi** [KoljaB/RealtimeTTS#129]
GPT-SoVITS is the best voice synthesis model I've ever seen.

**Comment by KoljaB** [comment]
Really want to try it, but can't get the partly chinese interface to work. Inference tab does not have a text box to enter the tts text. I can't find proper resources to explain how this works in english. 
I looked into the source code, probably would need to make some changes to get realtime inference. That code is some form of Elvish, I can't read it.

**Comment by SinlinLi** [comment]
> Really want to try it, but can't get the partly chinese interface to work. Inference tab does not have a text box to enter the tts text. I can't find proper resources to explain how this works in english. I looked into the source code, probably would need to make some changes to get realtime inference. That code is some form of Elvish, I can't read it.

Thank you for your try.

**Comment by SinlinLi** [comment]
> Really want to try it, but can't get the partly chinese interface to work. Inference tab does not have a text box to enter the tts text. I can't find proper resources to explain how this works in english. I looked into the source code, probably would need to make some changes to get realtime inference. That code is some form of Elvish, I can't read it.

Thank you for your attempt.

**Comment by SinlinLi** [comment]
> Really want to try it, but can't get the partly chinese interface to work. Inference tab does not have a text box to enter the tts text. I can't find proper resources to explain how this works in english. I looked into the source code, probably would need to make some changes to get realtime inference. That code is some form of Elvish, I can't read it.

Thank you for your attempt.
