### ISSUE TITLE
Is there a way to reset memory usage in server mode ?

### ISSUE THREAD

**Issue by Burnarz** [KoljaB/RealtimeTTS#132]
As said previously, many thanks for providing this project !!!

I'm using RealtimeTTS as a server, based on your async_server script, everything's fine execpt vRam usage growing accordling to usage. 
In half a day of testing got from ~2Go at start to ~5Go...
Is there a way of reseting vram usage without restarting the server ?

Again, many thanks

**Comment by KoljaB** [comment]
Tried to reproduce, can't see any VRAM leaks here. Need some further infos to pin this down. Which engine are you using (I guess Coqui)? Which OS is this occurring on? Which CUDA and torch versions are you using?

Could provide demo client code that loops some server functions and reproduces the problem? Reproducing for me without even knowing where to start seems nearly impossible (tested coqui for 20 min with automated script but did not see any VRAM leak here).
