### ISSUE TITLE
stream.stop() doesn't work

### ISSUE THREAD

**Issue by daswer123** [KoljaB/RealtimeTTS#14]
Hi, first of all thanks for your project, it is very cool to be able to get the result almost in realtime

I use CoquiEngine
I am using FastAPI and I have a problem that when I want to stop a stream and then restart stream, maybe with a different text, I can't do it.

After I do `stream.stop()` the subsequent `stream.play_async()` doesn't work and I have to restart the server to get everything working again.

To make it clearer, I recorded a small video and attached a simple server code

https://github.com/KoljaB/RealtimeTTS/assets/22278673/9aa2c581-7cad-410e-8b20-fb2f4b46cbc1

Here is a simple server code that demonstrates the problem
**server.py**
```
import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel
from RealtimeTTS import TextToAudioStream, CoquiEngine

app = FastAPI()

class SynthesisRequest(BaseModel):
    text: str

# Stopping occurs correctly, but when we start a new stream with new text, 
# we can't do anything with it, the stream stops playing and doesn't work anymore, 
# only restarting helps to fix it
@app.get("/tts_stop")
async def tts_stop():
    stream.stop()

# It works fine, but after we do stream.stop() it crashes and doesn't work anymore.
@app.post("/tts_to_audio")
async def tts_to_audio(request: SynthesisRequest):
    stream.feed(request.text)
    stream.play_async()

    return {"message": "stream"}

if __name__ == "__main__":
    engine = CoquiEngine()
    stream = TextToAudioStream(engine)

    uvicorn.run(app,port=8010)

```

**Comment by daswer123** [comment]
I saw your branch , had time to test a little, I'm not a master in python and I was able to do the intended only in this way, but it works )

My main idea was to be able to interrupt the current stream and start a new one and now it is possible, thanks

Here I wrote how I implemented it, in general it works as I need, but as I understand if it does not have time to clear the buffer and threads, it can create a problem, is it possible to process it somehow additionally to get a signal when you can send a new request to create a new stream?  Now it can be bypassed by a timer

part of **server.py**
```
@app.post("/tts_to_audio")
async def tts_to_audio(request: SynthesisRequest):
    global stream

    if stream.is_playing():
        stream.stop()
        time.sleep(2)

    stream = TextToAudioStream(engine)
    stream.feed(request.text)
    stream.play_async()
    return {"message": "stream"}


if __name__ == '__main__':
    engine = CoquiEngine()
    stream = TextToAudioStream(engine)

    uvicorn.run(app,port=8010)
```

https://github.com/KoljaB/RealtimeTTS/assets/22278673/28be7e11-d84c-479f-b51d-f103f704a8c7

**Comment by KoljaB** [comment]
Saw your post and yes, you were right. This still was not optimal. Will do another release to hopefully get this right this time.

**Comment by daswer123** [comment]
0.3.2 solved the problem I described completely
Now everything's perfect  :)

**Comment by KoljaB** [comment]
I'll look into that. Are you using the example fastapi server?
