### ISSUE TITLE
wav file cloning seems to not work

### ISSUE THREAD

**Issue by Wuzzooy** [KoljaB/RealtimeTTS#18]
Hello,

Since v0.3.0 the cloning on wav file seems to not work.
When it's a json file, it finds it and uses the voice accordingly but when when it's a wav file it fallback to the coqui_default_voice.

Thank you very much for your work.

**Comment by KoljaB** [comment]
Fixed it in v0.3.31. Thanks a lot for reporting, appreciated very much!
