### ISSUE TITLE
support chinese？

### ISSUE THREAD

**Issue by lonngxiang** [KoljaB/RealtimeTTS#2]

**Comment by KoljaB** [comment]
Would be a bit work to do this. The project is based on whisper, Zephyr-7B beta and Coqui XTTS model. 

As of my knowledge Whisper would understand chinese. The error rate would not be too great and it would probably work best with traditional chinese. For a better error rate it would be needed to switch the whole speech recognition to another model like whisper-large-zh-cv11, but this is another approach, not supported by faster_whisper and can't be integrated easily into RealtimeSTT.

Zephyr-7B could be changed with a model like bloomz-7b1 or chinese-llama-2-7b, which would require changes to the model prompt template handling. In principle not too hard to do, but without any understanding of the language the testing is not that easy.

Lastly Coqui needs to be switched to a chinese model like tts_models/zh-CN/baker/tacotron2-DDC-GST. I guess this would be the easiest part.

I'll think about this and maybe find a solution in the future.

**Comment by KoljaB** [comment]
Newest version v0.3.0 now supports simplified chinese. To test it, please update realtimetts version with `pip install realtimetts==0.3.0`.

Examples:
- [speed test](https://github.com/KoljaB/RealtimeTTS/blob/master/tests/pyqt6_speed_test_chinese.py) ([demo video](https://youtu.be/WHgj5etX5Zw))
- [cli test](https://github.com/KoljaB/RealtimeTTS/blob/master/tests/chinese_test.py) 

If something feels off (bugs, pronounciation or other issues with the implementation), please [mail](mailto:kolja.beigel@web.de) or send me a chat request on [reddit](https://www.reddit.com/user/Lonligrin). I'm not good in chinese and it's new, so I expect it to still have some problems. Most things can be fixed quite fast, I just need to know about them. 

If you like that stuff, a [twitter repost](https://twitter.com/LonLigrin/status/1729923757764903136) would be really awesome.

**Comment by lonngxiang** [comment]
> Newest version v0.3.0 now supports simplified chinese. To test it, please update realtimetts version with `pip install realtimetts==0.3.0`.
> 
> Examples:
> 
> * [speed test](https://github.com/KoljaB/RealtimeTTS/blob/master/tests/pyqt6_speed_test_chinese.py) ([demo video](https://youtu.be/WHgj5etX5Zw))
> * [cli test](https://github.com/KoljaB/RealtimeTTS/blob/master/tests/chinese_test.py)
> 
> If something feels off (bugs, pronounciation or other issues with the implementation), please [mail](mailto:kolja.beigel@web.de) or send me a chat request on [reddit](https://www.reddit.com/user/Lonligrin). I'm not good in chinese and it's new, so I expect it to still have some problems. Most things can be fixed quite fast, I just need to know about them.
> 
> If you like that stuff, a [twitter repost](https://twitter.com/LonLigrin/status/1729923757764903136) would be really awesome.

is this use Coquitts api?

**Comment by KoljaB** [comment]
> is this use Coquitts api? [https://github.com/coqui-ai/TTS](url)

Yes. It works with system tts, azure speech, elevenlabs and coqui tts.
