### ISSUE TITLE
 Elevenlabs only delivers mpeg

### ISSUE THREAD

**Issue by sharmt1411** [KoljaB/RealtimeTTS#215]
Hello, I see that the [elevenlab API](https://elevenlabs.io/docs/api-reference/streaming) now supports mp3 format. Do I still need to install mpv? Also, is the new API different fr
om the previous one? Can the current engine directly support it? 

<img width="379" alt="image" src="https://github.com/user-attachments/assets/53bd3dbb-03b0-42dc-a7f4-0f94ac505a7a">

**Comment by KoljaB** [comment]
They always supported mp3, in fact for lower tiers they only deliver mp3 (and not wav). Mp3 format is the main reason we need mpv, because it can realtime play those chunks. Current engine should support it because it was always this way.
