### ISSUE TITLE
Is there any ways to make Realtime Streaming to Client?

### ISSUE THREAD

**Issue by bellkjtt** [KoljaB/RealtimeTTS#228]
Hi, I'm Trying to make LLM + Realtime TTS App Service.

This Project is wonderful, however, i can't find the Audio Chunk making def or other functions. 
The only output function is playing Localy with Play_async or play.
What I want to make is that the Application server that connected with client, and stream the Audio chunk, send to the Client in Realtime.

Is there any way to make this with your project? Thks for reading.

**Comment by KoljaB** [comment]
Sure, that's definitely possible. You can create a `TextToAudioStream` with the `muted=True` parameter, which prevents the system from opening an output audio device stream. Then, use the `play` method with `muted=True` and implement the `on_audio_chunk` callback. Within this callback, you can process each audio chunk and send it to the client in real-time. 

To proper handle the audio data, you may want to retrieve the format, channel count, and sample rate from the engine that you use. This way you can process and adapt the chunk appropriately for the client, such as converting it to `int16` or `float32`, or resampling it as needed.

Example:
```python
audio_format, channels, sample_rate = self.engine.get_stream_info()
```

**Comment by remichu-ai** [comment]
I tried to follow the example in the fastapi server script and encounter this error when it set `muted=True`

```
File "/home/remichu/miniconda3/envs/mlenv_vision/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/remichu/miniconda3/envs/mlenv_vision/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/remichu/miniconda3/envs/mlenv_vision/lib/python3.12/site-packages/RealtimeTTS/stream_player.py", line 505, in _process_buffer
    self._play_chunk(chunk)
  File "/home/remichu/miniconda3/envs/mlenv_vision/lib/python3.12/site-packages/RealtimeTTS/stream_player.py", line 444, in _play_chunk
    resampled_data = resampy.resample(audio_data, self.audio_stream.config.rate, self.audio_stream.actual_sample_rate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remichu/miniconda3/envs/mlenv_vision/lib/python3.12/site-packages/resampy/core.py", line 102, in resample
    raise ValueError("Invalid sample rate: sr_new={}".format(sr_new))
ValueError: Invalid sample rate: sr_new=0
Exception in thread Thread-6 (generate_audio):
```

**Comment by KoljaB** [comment]
I think that is a bug I accidentally introduced in one of the former versions. Could you update to the latest version and try again please?

**Comment by remichu-ai** [comment]
Yes, upgrade to latest version solved the problem. Thanks
