### ISSUE TITLE
async not working as expected?

### ISSUE THREAD

**Issue by beetree** [KoljaB/RealtimeTTS#23]
This code:
```
stream = TextToAudioStream(engine)
stream.feed("Hello")
stream.play_async()
time.sleep(0.1)
stream.feed("friend")
if stream.is_playing():
    stream.play_async()
```

... does only play "hello" and not "friend". However, if I comment out time.sleep() it plays both. Also, if I sleep for 2+ seconds it also plays both words.

Is this expected?

**Comment by KoljaB** [comment]
Not expected, thanks for pointing this out. Should be fixed with the new version.

**Comment by beetree** [comment]
Nice, thanks!
