### ISSUE TITLE
Extremely slow audio playback

### ISSUE THREAD

**Issue by olivernaaris** [KoljaB/RealtimeTTS#231]
Hi

I have a setup where I have a Python backend using RealtimeTTS for streaming audio from Azure Speech services to a Next.js frontend with websockets.
Python backend is deployed on Fly.io and the frontend to Vercel.

Testing the stack locally on my MacBook and everything works perfectly.
However when I deploy the frontend code to Vercel and backend code to Fly.io VPS, I get audio playback that is extremely slow.
The backend receives the audio recording from Azure with SampleRate: 16000, bitDepth: 16, numChannels: 1
The backend then forwards the audio as PCM data with the same sample rate, bit depth and channels to the frontend. The frontend then resamples the audio from 16000hz to 48000hz, so it can be played on the browser.
I have added the audio recording to the issue as well.
Everything works perfectly fine with the same code on my local environment...but not when it's deployed to the actual environment.

I initially thought that maybe it's because of network latency, but I tested it out by using Chrome dev tools with network throttling to simulate slow internet speed and latency locally - everything worked fine.

Any ideas what might be wrong?

https://github.com/user-attachments/assets/551176f3-ffa9-415e-9ea9-7a270c17faf0

**Comment by KoljaB** [comment]
Hard to say but it sounds like if you play 48kHz audio on a way lower (16 or 24) kHz output device. What happens if you skip the upsampling?

**Comment by olivernaaris** [comment]
I configured the Python backend code to write audio sample into the filesystem. I can see that on my local machine the audio file has 16kHz sample rate, which is expected. However on the Fly.io machine the audio sample file has 48kHz.
So it seems to me that the audio coming from Azure is already with 48kHz sample rate.
I'm honestly confused where the difference is coming from as the code is the same and the same Azure endpoint should give the same sample rate.
From RealtimeTTS Azure engine code it seems that it's not possible to set the speech synthesis output format?
I'm guessing that for some reason Azure API is in some cases giving 16kHz and other cases 48kHz audio.
Would it be possible to customize Azure engine output format in the code to try other options as documented here?
https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechsynthesisoutputformat?view=azure-dotnet

**Comment by olivernaaris** [comment]
Another update. I was running the application Python process on my MacBoook Pro directly and the audio playback worked correctly.
I then decided to try to run my Python backend locally in a docker container (same Dockerfile as I'm using for staging & production) and I was finally able to reproduce the issue.
Running in a dockerized environment the audio is returned from Azure with sample rate 48kHz.
I'm using this docker image: python:3.11-slim
And i'm installing these packages in my dockerfile:
ffmpeg 7:5.1.6-0+deb12u1
portaudio19-dev 19.6.0-1.2
libportaudio2 19.6.0-1.2
python3-pyaudio 0.2.13-1+b1

I'm guessing that there is some difference between the packages on my Mac and in the Linux docker environment and that causes the Azure client to return the audio in a different sample rate.

**Comment by KoljaB** [comment]
Thank you for this interesting information. 

To address this, the `AzureEngine` in RealtimeTTS would need to call `set_speech_synthesis_output_format` with one of the following formats: `riff-16khz-16bit-mono-pcm`, `riff-24khz-16bit-mono-pcm`, or `riff-48khz-16bit-mono-pcm`. These formats would need to be configurable through the `AzureEngine` constructor. Additionally, the correct sample rate info should be provided by the engine via the `get_stream_info` method.

This is a valid issue and a useful feature to add, so I’ll integrate it in the near future. If you’re up for it, I’d be more than happy to take a PR with the required changes.

**Comment by KoljaB** [comment]
Will release a new RealtimeTTS version this evening that will allow to generate 48kHz with Azure explicitly too.

**Comment by vbmcpy** [comment]
Hello, I have the same case but I'm using the coqui engine, will this pr also adjust for coqui in 22000 16 or 8bit? comes out well in slow motion

**Comment by vbmcpy** [comment]
coqui_engine = create_coqui_engine(voice_path)
        stream = TextToAudioStream(coqui_engine)
        stream.feed(iter([text]))

        output_file = f"{coqui_engine.engine_name}_output_{requested_voice.split('.')[0]}.wav"
        output_path = os.path.join(OUTPUT_DIR, output_file)

        stream.play(output_wavfile=output_path)
        coqui_engine.shutdown()

        return send_file(output_path, as_attachment=True, mimetype='audio/wav')

**Comment by KoljaB** [comment]
v0.4.20 now adresses 48kHz for Azure.

---

> Hello, I have the same case but I'm using the coqui engine, will this pr also adjust for coqui in 22000 16 or 8bit? comes out well in slow motion

Coqui XTTS always synthesizes at 24000 Hz and 32-bit. That’s just how the model works, so it’s not something you can tweak. If the playback feels slow, it’s probably not about the sample rate. 

From what I see in your code, you’re synthesizing into a file and then sending that file. You might want to stream the audio chunks in real-time while they’re being generated instead. Unlike StyleTTS, Coqui’s XTTS model actually supports real-time streaming, so that could fix your issue.

Also, if you’re not using **DeepSpeed**, you’re missing out: it can speed up Coqui inference by about 2x. On Linux, just run:

```bash
pip install deepspeed
```

For Windows, use these commands instead:

```bash
pip install torch==2.1.2+cu121 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
pip install https://github.com/daswer123/deepspeed-windows-wheels/releases/download/11.2/deepspeed-0.11.2+cuda121-cp310-cp310-win_amd64.whl
```

Try those and see how it works!

**Comment by olivernaaris** [comment]
Hey
With the new version and a fixed audio_format, it works well now.
Thank you so much for the quick fix!
