### ISSUE TITLE
in linux docker

### ISSUE THREAD

**Issue by sharmt1411** [KoljaB/RealtimeTTS#235]
Hello, I have a question: Can this run in a Linux Docker environment? Why does the code that works on Windows fail to run when moved to Linux? The error message is as follows:
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory

I asked GPT，it said that the problem appears to be audio-related and needs specific host machine permissions. Since I'm working with a rented server for testing, I don't have access to grant these permissions.
What puzzles me is that I've already set muted=true in the play method and defined an output directory, yet it still requires audio devices. And I use GTTS，still has the problem。 Is there something wrong somewhere Thanks.

**Comment by KoljaB** [comment]
The issue occurs because you need to set muted=True in the TextToAudioStream constructor as well. I can't only provide this in the play method, because opening up the stream after calling play would add latency. Setting muted=True in the constructor ensures the stream is properly initialized without accessing any audio devices.

The play method does have a muted flag for toggling between muted and playback modes during runtime, not for suppressing audio device usage upfront.

**Comment by sharmt1411** [comment]
thanks for your reply, this problem solved.thanks again！

**Comment by sharmt1411** [comment]
> The issue occurs because you need to set muted=True in the TextToAudioStream constructor as well. I can't only provide this in the play method, because opening up the stream after calling play would add latency. Setting muted=True in the constructor ensures the stream is properly initialized without accessing any audio devices.
> 
> The play method does have a muted flag for toggling between muted and playback modes during runtime, not for suppressing audio device usage upfront.

hello, i found that if set TextToAudioStream constructor muted true ,then AudioStream.actual_sample_rate will be 0,because AudioStream.openstream will not run _get_best_sample_rate,and cause some problem
`File "D:\pythonproject\Aispeakingpractice\.venv\Lib\site-packages\RealtimeTTS\stream_player.py", line 505, in _process_buffer
    self._play_chunk(chunk)
  File "D:\pythonproject\Aispeakingpractice\.venv\Lib\site-packages\RealtimeTTS\stream_player.py", line 444, in _play_chunk
    resampled_data = resampy.resample(audio_data, self.audio_stream.config.rate, self.audio_stream.actual_sample_rate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonproject\Aispeakingpractice\.venv\Lib\site-packages\resampy\core.py", line 102, in resample
    raise ValueError("Invalid sample rate: sr_new={}".format(sr_new))
ValueError: Invalid sample rate: sr_new=0`

**Comment by KoljaB** [comment]
This should already be fixed in the new version (see this [code](https://github.com/KoljaB/RealtimeTTS/blob/3684c123589527faf8ed6d39f7f04c19f08ac76c/RealtimeTTS/stream_player.py#L441-L450) with protection against actual_sample_rate being 0).

Are you using v0.4.21?

**Comment by sharmt1411** [comment]
i used v0.4.17,thanks~
