### ISSUE TITLE
How to just Generate the .wav chunks but not playback the audio automaticlty. 

### ISSUE THREAD

**Issue by mercuryyy** [KoljaB/RealtimeTTS#26]
stream.play_async()

logic how can we just start creating the chunks but not initiate the playback of the audio files.

I already added logic in 

 for i, chunk in enumerate(chunks):

to save the chunks in a folder, but i cant find a simple way to stop the playback without breaking stuff.

**Comment by KoljaB** [comment]
stream.play_async(muted=True) should do that

**Comment by mercuryyy** [comment]
thanks, will that just mute the audio but still run the playback? i am trying to save on latency and resources would want to completely disable the playback.

**Comment by KoljaB** [comment]
With muted=True no data gets written to the output stream. So there is no "silent" playback (where it would lower the volume to 0 or so), it only synthesizes the audio chunks.

**Comment by mercuryyy** [comment]
Thank you @KoljaB great support and Repo!
