### ISSUE TITLE
Can we use on_audio_chunk callback as input data in realtime service？

### ISSUE THREAD

**Issue by jacobtang** [KoljaB/RealtimeTTS#36]
play(self,
            fast_sentence_fragment: bool = True,
            buffer_threshold_seconds: float = 0.0,
            minimum_sentence_length: int = 10,
            minimum_first_fragment_length : int = 10,
            log_synthesized_text = False,
            reset_generated_text: bool = True,
            output_wavfile: str = None,
            on_sentence_synthesized = None,
            on_audio_chunk = None,
            tokenizer: str = "nltk",
            language: str = "en",
            context_size: int = 12,
            muted: bool = False,
            ):
 I need to use the on_audio_chunk data as input data in realtime service，can I just use the callback data，but not use the system to play audio？
thanks！

**Comment by KoljaB** [comment]
Yes, use the on_audio_chunk callback together with the muted=True parameter.

**Comment by jacobtang** [comment]
I try to use "stream.play_async" for get the "on_audio_chunk",but no call back data output,can you take some samples code,thanks!
def on_audio_chunk_callback(chunk):
        print("on_audio_chunk_callback",chunk)
        send_to_client(chunk)
        print("send_to_client chunk")

def process_text(text):
        user_message = {'role': 'user', 'content': text}
        # Get assistant response and play it
        translation_stream = generate_response([system_prompt_message, user_message])
        if stream is not None:
            print("stream is not None,go stream.feed and play")
            stream.feed(translation_stream)
            stream.play_async(tokenizer="stanza",language="zh",on_audio_chunk=on_audio_chunk_callback,muted=True)

**Comment by KoljaB** [comment]
Hey Jacob,

I would need to see more code to find the issue.

This is how minimal code for on_audio_chunk in chinese would look like:
```python
from RealtimeTTS import TextToAudioStream, SystemEngine
import time

def dummy_generator():
    yield "我喜欢读书。天气很好。我们去公园吧。今天是星期五。早上好。这是我的朋友。请帮我。吃饭了吗？我在学中文。晚安。"

def on_audio_chunk_callback(chunk):
    print(f"Chunk received, len: {len(chunk)}")

engine = SystemEngine(voice="Huihui")
stream = TextToAudioStream(engine).feed(dummy_generator())
stream.play_async(tokenizer="stanza", language="zh", on_audio_chunk=on_audio_chunk_callback, muted=True)

while stream.is_playing():
    time.sleep(0.1)
```

The parts you posted look correct and should work, so I guess most probably there's something wrong with the generate_response method. Could you rule this out by checking if it does play out correctly when removing the on_audio_chunk and muted=True parameters?

**Comment by jacobtang** [comment]
client = OpenAI(
                api_key=os.environ["OPENAI_API_KEY"]
              )
              engine = ElevenlabsEngine()
              engine.set_api_key("xxxx")
              stream = TextToAudioStream(engine)
             # voices = engine.get_voices()
             # for index, voice in enumerate(voices, start=1):
             #     print(f"engine.get_voices:  {index}. {voice}")
      
              #stream = TextToAudioStream(engine, log_characters=True)
      
              user_message = {'role': 'user', 'content': 'Translate the given text to chinese. Output only the translated text'}
      
              translation_stream = generate_response([system_prompt_message, user_message])
      
              for chunk in translation_stream:
                  print("Received chunk:", chunk)
      
              stream = TextToAudioStream(engine, log_characters=True).feed(translation_stream)
      
              stream.play_async(tokenizer="stanza",language="zh",on_audio_chunk=on_audio_chunk_callback,muted=True)``

**Comment by jacobtang** [comment]
may be something wrong with ElevenlabsEngine? generate_response can return correct data

**Comment by KoljaB** [comment]
ElevenlabsEngine seems fine to me. I tried:
```python
from RealtimeTTS import TextToAudioStream, ElevenlabsEngine
import time
import os

def dummy_generator():
    yield "我喜欢读书。天气很好。我们去公园吧。今天是星期五。早上好。这是我的朋友。请帮我。吃饭了吗？我在学中文。晚安。"

def on_audio_chunk_callback(chunk):
    print(f"Chunk received, len: {len(chunk)}")

engine = ElevenlabsEngine(os.environ.get("ELEVENLABS_API_KEY"))
stream = TextToAudioStream(engine).feed(dummy_generator())
stream.play_async(tokenizer="stanza", language="zh", on_audio_chunk=on_audio_chunk_callback, muted=True)

while stream.is_playing():
    time.sleep(0.1)
```

Which gave me this output:
```
Chunk received, len: 26635
Chunk received, len: 27611
Chunk received, len: 27559
Chunk received, len: 27604
Chunk received, len: 27604
Chunk received, len: 27685
```

Chunks are delivered, so error must still be somewhere else in the code - I guess?

**Comment by jacobtang** [comment]
Exception in thread Thread-1 (play):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/RealtimeTTS/text_to_stream.py", line 231, in play
    self.engine.synthesize(self.char_iter)
  File "/usr/local/lib/python3.10/dist-packages/RealtimeTTS/engines/elevenlabs_engine.py", line 121, in synthesize
    self.stream(self.audio_stream)
  File "/usr/local/lib/python3.10/dist-packages/RealtimeTTS/engines/elevenlabs_engine.py", line 177, in stream
    for chunk in audio_stream:
  File "/usr/local/lib/python3.10/dist-packages/elevenlabs/api/tts.py", line 134, in generate_stream_input
    if data["audio"]:
KeyError: 'audio'

I used the same example code as you, but encountered the above error. Is it because I used an incompatible version?

**Comment by KoljaB** [comment]
Probably some version issues, yes, but hard to say since the error occurs within the elevenlabs code (elevenlabs/api/tts.py).

Above code works here on a fresh env on Python 3.11.4 with a fresh installed RealtimeTTS:

```bash
python -m venv test_env
test_env\Scripts\activate
pip install realtimetts
python test_on_audio_chunk_callback_eleven.py
Chunk received, len: 26642
Chunk received, len: 27619
...
```

This error hints to something getting wrong with generating the audio within elevenlabs:
```bash
if data["audio"]:
KeyError: 'audio'
```

In my experience this can happen when a submitted generator is misformed or fails to yield tokens in time. But it should not happen with the given code, since this is a very basic generator, so there must be another issue.

**Comment by jacobtang** [comment]
Thank you very much for your help！
still have some problem with ElevenlabsEngine, I change to use OoenAIEngine, the callback audio chunk_size = 1024，is it nomal,and what should be the return audio format?16k,mono,int16 bit?

**Comment by KoljaB** [comment]
OpenAI also delivers mp3 chunks, but - not like Elevenlabs chunks - they can be converted to pcm, which is done in _play_chunk method of stream_player.py.
The sample rate is 22050 and chunks are mono after that. You can see this via get_stream_info method of every engine. Chunks size 1024 is normal for every engine that yields wav or can be converted to (all but Elevenlabs).

**Comment by jacobtang** [comment]
resolved.
