### ISSUE TITLE
Install error on Windows - Microsoft Visual C++ 14.0 or greater is required.

### ISSUE THREAD

**Issue by Fredrum** [KoljaB/RealtimeTTS#40]
Hello!
This seems like a very cool project! :)  I'm trying to test it out for this little game thing I'm doing but I get an error message when trying to install on Windows 11.  (from inside pycharm venv)

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Does this seem correct to you? 
Would I really need to install MSVC for python RealtimeTTS ?

Thank you for making your work public!

Cheers!
Fred

**Comment by Fredrum** [comment]
Hi and thank you for the reply!
I started a fresh python project and went from the top.

It was 'TTS' install that threw the error,

>   copying TTS\vocoder\utils\__init__.py -> temp_build\TTS\vocoder\utils
>   copying TTS\vocoder\utils\distribution.py -> temp_build\TTS\vocoder\utils
>   copying TTS\vocoder\utils\generic_utils.py -> temp_build\TTS\vocoder\utils
>   running build_ext
>   building 'TTS.tts.utils.monotonic_align.core' extension
>   error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>   [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for TTS
> ERROR: Could not build wheels for TTS, which is required to install pyproject.toml-based projects

**Comment by KoljaB** [comment]
It's the coqui engine (TTS==0.22.0), I can see that from the logs. This one performs local TTS to their excuse. Not much I can do here. If it needs to compile, there's nothing I can do besides remove it.

**Comment by Fredrum** [comment]
Ok I see. I think many people who try this might already have those MS tools installed. My computer is pretty new so I don't have much installed on it yet. Thanks for looking into.

**Comment by PylotLight** [comment]
I'd love a way to have this work on linux with no windows c++ required instead, but I might create a separate issue for that.

**Comment by KoljaB** [comment]
There must be something we're missing here. TTS library ist tested [under ubuntu](https://docs.coqui.ai/en/latest/installation.html), so it should not per default require microsoft stuff.
