### ISSUE TITLE
Can I use this in Flask Python webapp?

### ISSUE THREAD

**Issue by eraclioone** [KoljaB/RealtimeTTS#52]
Hello, thanks for your work first.

Can I use this in Flask Python webapp?

I'm going to send request to Flask app from JS to get audio streaming.

Is this possible as well?

Hope to hear from you soon.

**Comment by KoljaB** [comment]
Should be quite straighforward with flask, since it's not async stuff like FastAPI (where I'd expect things to get more complicated). Haven't implemented anything like this so far, but I don't see reasons why this shouldn't work.

**Comment by rrrajat04** [comment]
@eraclioone were you able to stream it using flask , I did something similar but the voice chunks are not playing in the UI , also if I write the chunks to a file then also the file is not playing? Can you share any code for reference if it's possible for you. Thanks in advance.
