### ISSUE TITLE
Pyaudio error while installing RealtimeTTS module

### ISSUE THREAD

**Issue by eraclioone** [KoljaB/RealtimeTTS#54]
![image](https://github.com/KoljaB/RealtimeTTS/assets/163383962/cd427626-022b-48e6-9ab8-8f76f9461e63)

Why is this come out?

**Comment by KoljaB** [comment]
Looks like installation of PyAudio failed (some issue with building the package from source). You could try to resolve using:

```bash
sudo apt-get update
sudo apt-get install gcc
sudo apt-get install libasound-dev
sudo apt-get install python3-pyaudio
```

These should install GCC compiler, ALSA lib dev files, and the PyAudio package without needing to compile from source. For more infos about PyAudio installation on Linux, pls refer to the [PyAudio installation documentation](https://people.csail.mit.edu/hubert/pyaudio/#downloads).

**Comment by eraclioone** [comment]
Thanks for your kind response. By the way,  can torch work on any vps or virtual machines?

**Comment by eraclioone** [comment]
![image](https://github.com/KoljaB/RealtimeTTS/assets/163383962/84b469ac-4d67-4237-b758-897fd7fcdb2c)
It always shows this. 'killed'

**Comment by KoljaB** [comment]
No idea about torch and vps, i have zero experience with that. Could be memory related, maybe adding swap space helps. But this is so linux related and I am a noob on this platform.
