### ISSUE TITLE
Voice cloning procedure.

### ISSUE THREAD

**Issue by BracerJack** [KoljaB/RealtimeTTS#58]
The front page says:
to clone a voice submit the filename of a wave file containing the source voice as cloning_reference_wav to the CoquiEngine constructor.

This code works, where do I put the cloning_reference_wav? Thanks
if __name__ == '__main__':
	from RealtimeTTS import TextToAudioStream, CoquiEngine

	import logging
	logging.basicConfig(level=logging.INFO)    
	engine = CoquiEngine(level=logging.INFO)

	stream = TextToAudioStream(engine)
    
	print ("Starting to play stream")
	stream.feed("Everything is going perfectly")
	stream.play() #pause(), resume(), stop()

	engine.shutdown()

**Comment by KoljaB** [comment]
Ups sorry. I changed the parameter name from "cloning_reference_wav " to "voice" in [v0.3.40](https://github.com/KoljaB/RealtimeTTS/releases/tag/v0.3.40) - but forget to update it in the front page. 

So in your code you'd change:
```python
engine = CoquiEngine(level=logging.INFO)
```
to
```python
engine = CoquiEngine(level=logging.INFO, voice="example_voicefile.wav")
```

**Comment by BracerJack** [comment]
It works! Thank you!

It is real time and it sound even better than my other local voice model projects, this is awesome.

There is still a little stutter [have to wait a little for the next few words] but it is understandable because it is real time and I am using cpu.

Is there a way to channel the output into a wav file ?

**Comment by KoljaB** [comment]
Happy to hear that it works. You can use output_wavfile parameter from the play and play_async methods to write into a file. 

And yes, sadly CPU synthesis for coqui XTTS is too slow for realtime.

**Comment by KoljaB** [comment]
Example:
https://github.com/KoljaB/RealtimeTTS/blob/master/tests/write_to_file.py

**Comment by BracerJack** [comment]
It works.             
The sound quality is SIGNIFICANTLY BETTER than the non Realtime version that I have been using.   
Please also use 44100Hz 16bit, the quality pulls through VERY WELL.

Since it is writing to file: stream.play(output_wavfile="Output1.wav"), is there a way to make it not play it out while it is writing to the wav file? The quality is SO GOOD I rather just wait for the wav file to be out.

Thank you for your excellent work.

**Comment by KoljaB** [comment]
You can set the muted parameter of the play and play_async methods to true to silently play into a file.

Thank you for your kind words.
