### ISSUE TITLE
Does adding Google gTTS support make sense?

### ISSUE THREAD

**Issue by impredicative** [KoljaB/RealtimeTTS#63]
Does adding Google [gTTS](https://pypi.org/project/gTTS/) support make sense?

**Comment by KoljaB** [comment]
Yeah, good question. Does seem like not that bad candidate for me. I wonder if people actually use this.

**Comment by KoljaB** [comment]
Strong arguments. I think I'll integrate that one.

**Comment by KoljaB** [comment]
Available now since v0.4.0
