### ISSUE TITLE
[Feature request] Ability to specify the output device 

### ISSUE THREAD

**Issue by daswer123** [KoljaB/RealtimeTTS#64]
Hi, I'm doing a project now, and I really need to be able to specify the output device (I want to output to a virtual microphone) the result of streaming.

It would be cool if it would be possible to specify the output device as it is done in RealtimeSTT with the input device.

Thanks for your work )

**Comment by KoljaB** [comment]
Oops, fixed it in parallel. Code is on, new output_device_index parameter for TextToAudioStream, thx for issue and PR :)

**Comment by daswer123** [comment]
Great )
