### ISSUE TITLE
Pyaudio package is not building 

### ISSUE THREAD

**Issue by SaranDharshanSP** [KoljaB/RealtimeTTS#81]
![image](https://github.com/KoljaB/RealtimeTTS/assets/126688534/f5f4f129-2de0-4593-8a19-83df9970b097)
You could see it doesnt build the Pyaudio package

**Comment by KoljaB** [comment]
Hey there.  

On Mac pls try:
```python
brew install portaudio
pip install pyaudio
```

On Linux/Unix-like systems pls try:
```python
sudo apt-get install portaudio19-dev
pip install pyaudio
```

If that does not work, you could try to install conda and install pyaudio with:
```python
conda install pyaudio
```

If you're on windows you can also install pipwin and try the (unofficial) python package binaries for windows provided by Christoph Gohlke:
```python
pip install pipwin
pipwin install pyaudio
```

**Comment by SaranDharshanSP** [comment]
Yup this solved the issue. Thank you!
