### ISSUE TITLE
Can this TTS produce natural sounding laughter and other human sounds? Also does this TTS have changeable parameters?

### ISSUE THREAD

**Issue by PhilipAmadasun** [KoljaB/RealtimeTTS#87]
Is it possible to produce decent human like laughter and other noises with this TTS? Are there some changeable parameters I can mess around with to try to get what I want?

**Comment by KoljaB** [comment]
Hey, thanks for your interest in RealtimeTTS! 

This library serves as an interface to bring real-time capabilities to several underlying TTS engines, including OpenAI TTS, Elevenlabs, Azure Speech Services, Coqui TTS, gTTS, and System TTS. RealtimeTTS itself does not generate any speech sounds, it integrates these existing engines.
 
The mentioned TTS engines don't support features like producing laughter, crying and other non-speech sounds. They are typically not covered by traditional TTS technology (maybe Bark can do that but I don't think so). If you want to include such sounds in your projects, you might consider using samples of human noises that can be played alongside the TTS output. I think this would probably be the most effective way to achieve that.

Thank you for reaching out, and please let us know if you have any other questions!
