### ISSUE TITLE
Is it possible RealtimeTTS support VITS?

### ISSUE THREAD

**Issue by Rares9999** [KoljaB/RealtimeTTS#92]
Hi, RealtimeTTS running coqui with XTTS, is that possible running coqui with VITS, with streaming features?

If it is possible, how to implement VITS?

**Comment by KoljaB** [comment]
Unlike XTTS VITS does not offer streaming inference out of the box. While it would be possible to offer sentence by sentence inference the latency would not be great. I aim for sub 1 second latency for an engine to be integrated into RealtimeTTS. VITS would very probably not achieve this without input streaming, so I feel it isn't worth the amount of work I would need to put into this.
