### ISSUE TITLE
pyinstaller pack issue！！！

### ISSUE THREAD

**Issue by mzly1212** [KoljaB/RealtimeTTS#93]
![屏幕截图 2024-06-13 131646](https://github.com/KoljaB/RealtimeTTS/assets/140771641/0c0d5e48-2acd-4f46-b36f-e456bdcb4c11)
I packaged this project using pyinstaller but it doesn't work
How to fix this, please

**Comment by mzly1212** [comment]
@KoljaB Looks like the default  "Microsoft.CognitiveServices.Speech.core.dll"  path is wrong, Can I change its default path？？？

**Comment by KoljaB** [comment]
No clue

**Comment by criminact** [comment]
@mzly1212  Can you provide your PyInstaller script to package this? I will take a look.

**Comment by mzly1212** [comment]
> @mzly1212 Can you provide your PyInstaller script to package this? I will take a look.

I just tried to package it with a simple example, such as:
`from RealtimeTTS import TextToAudioStream, SystemEngine
engine = SystemEngine(voice="Huihui")
stream = TextToAudioStream(engine)
stream.feed('你好').play_async()`
with the pyinstaller command: `pyinstaller -F -w <filename>`

**Comment by mzly1212** [comment]
> @mzly1212 Can you provide your PyInstaller script to package this? I will take a look.

when i run the exe after packaged, it went wrong and showed:
![image](https://github.com/user-attachments/assets/afb1b787-1ca4-4bb6-8b97-430d6ab640f4)

**Comment by mzly1212** [comment]
> @mzly1212 Can you provide your PyInstaller script to package this? I will take a look.

 it showed the default  path of **Microsoft.CognitiveServices.Speech.core.dll** is wrong, but I don't know how to designate its path

**Comment by criminact** [comment]
Here is what you can try - 

1. Get this [Nuget Package](https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech), locate the dll - Microsoft.CognitiveServices.Speech.core.dll
2. Run pyinstaller -F --add-binary <path to Microsoft.CognitiveServices.Speech.core.dll>;. -w <filename>

Does this work?

**Comment by mzly1212** [comment]
> Here is what you can try -
> 
> 1. Get this [Nuget Package](https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech), locate the dll - Microsoft.CognitiveServices.Speech.core.dll
> 2. Run pyinstaller -F --add-binary `<path to Microsoft.CognitiveServices.Speech.core.dll>`;. -w `<filename>`
> 
> Does this work?

i use `pyinstaller --add-data "D:\Python-Code\RealtimeTTS\venv\Lib\site-packages\azure:."  -F `
**it work!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**
thank u so much ٩(๑•̀ω•́๑)۶

**Comment by criminact** [comment]
Ah cool. We can close this issue.
